# Generated by Django 2.0.3 on 2018-03-28 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_article_comment_subcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 28, 22, 23, 0, 388230)),
        ),
        migrations.AddField(
            model_name='article',
            name='released',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
