# Generated by Django 2.0.3 on 2018-03-30 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180328_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pic_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='pic_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.ImageField(blank=True, height_field='pic_height', null=True, upload_to='', width_field='pic_width'),
        ),
        migrations.AlterField(
            model_name='article',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 30, 16, 16, 1, 633281)),
        ),
    ]
