# Generated by Django 2.0.3 on 2018-04-01 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180330_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='overview',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 1, 14, 35, 31, 763149)),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
