# Generated by Django 2.0.3 on 2018-04-02 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180401_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextension',
            name='favorite_categories',
        ),
        migrations.RemoveField(
            model_name='userextension',
            name='picture',
        ),
        migrations.AlterField(
            model_name='article',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 2, 18, 45, 27, 646862)),
        ),
    ]
