# Generated by Django 2.0.3 on 2018-04-15 12:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_auto_20180414_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_article_like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.CharField(choices=[('UP', 'Upvote'), ('DOWN', 'Downvote'), ('NONE', 'NotVoted')], max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 15, 14, 11, 20, 313439)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 15, 14, 11, 20, 314940)),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 15, 14, 11, 20, 314940)),
        ),
        migrations.AddField(
            model_name='user_article_like',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Article'),
        ),
        migrations.AddField(
            model_name='user_article_like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
