# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-28 12:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180416_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 14, 25, 14, 184718)),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 14, 25, 14, 185718)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 28, 14, 25, 14, 186718)),
        ),
        migrations.AlterField(
            model_name='subcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voter',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Article'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voter',
            name='value',
            field=models.BooleanField(default=False),
        ),
    ]
